CREATE TABLE IF NOT EXISTS `USERS` (
  `id` INTEGER NOT NULL AUTO_INCREMENT ,
  `email` VARCHAR(50) NULL DEFAULT NULL ,
  `name` VARCHAR(50) NULL DEFAULT NULL ,
  `password` VARCHAR(50) NULL DEFAULT NULL ,
  `oauth_token` LONGTEXT NULL DEFAULT NULL ,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `CLASSROOMS` (
  `id` INTEGER NOT NULL AUTO_INCREMENT ,
  `name` VARCHAR(50) NULL DEFAULT NULL ,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `NOTES` (
  `id` INTEGER NOT NULL AUTO_INCREMENT ,
  `attachment` LONGTEXT NULL DEFAULT NULL ,
  `created_at` TIMESTAMP ,
  `user_id` INTEGER NULL DEFAULT NULL
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `SAVED` (
  `id` INTEGER NOT NULL AUTO_INCREMENT ,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `CLASS-USERS JOIN` (
  `id` INTEGER NOT NULL AUTO_INCREMENT ,
  `user_id` INTEGER NULL DEFAULT NULL ,
  `classroom_id` INTEGER NULL DEFAULT NULL
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `TAG-NOTES JOIN` (
  `id` INTEGER NOT NULL AUTO_INCREMENT ,
  `tag_id` INTEGER NULL DEFAULT NULL ,
  `note_id` INTEGER NULL DEFAULT NULL
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `SAVED-NOTES JOIN` (
  `id` INTEGER NOT NULL AUTO_INCREMENT ,
  `saved_id` INTEGER NULL DEFAULT NULL ,
  `note_id` INTEGER NULL DEFAULT NULL
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `CLASS-NOTES JOIN` (
  `id` INTEGER NOT NULL AUTO_INCREMENT ,
  `classroom_id` INTEGER NULL DEFAULT NULL ,
  `note_id` INTEGER NULL DEFAULT NULL
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `TAGS` (
  `id` INTEGER NOT NULL AUTO_INCREMENT ,
  `name` VARCHAR(50) NULL DEFAULT NULL ,
  PRIMARY KEY (`id`)
);

ALTER TABLE `NOTES` ADD FOREIGN KEY (`user_id`) REFERENCES 'USERS'('id');
ALTER TABLE `CLASS-NOTES JOIN` ADD FOREIGN KEY (`classroom_id`) REFERENCES `CLASSROOMS`(`id`);
ALTER TABLE `CLASS-NOTES JOIN` ADD FOREIGN KEY (`note_id`) REFERENCES `NOTES`(`id`);
ALTER TABLE 'CLASS-USERS JOIN' ADD FOREIGN KEY (`classroom_id`) REFERENCES `CLASSROOMS`(`id`);
ALTER TABLE `CLASS-USERS JOIN` ADD FOREIGN KEY (`user_id`) REFERENCES 'USERS'('id');
ALTER TABLE `TAG-NOTES JOIN` ADD FOREIGN KEY (`note_id`) REFERENCES 'NOTES'('id');
ALTER TABLE `TAG-NOTES JOIN` ADD FOREIGN KEY (`tag_id`) REFERENCES 'TAGS'('id');
ALTER TABLE `SAVED-NOTES JOIN` ADD FOREIGN KEY (`note_id`) REFERENCES 'NOTES'('id');
ALTER TABLE `SAVED-NOTES JOIN` ADD FOREIGN KEY (`tag_id`) REFERENCES 'TAGS'('id');


